# Rendered by envsubst -> values/values-prod.yaml

# Global ingress behavior
global:
  # IngressClass used by the chart's ingresses
  ingressClassName: nginx

# Onyxia chart values (web + api)
onyxia:
  web:
    # Public hostname for the UI
    host: ${ONYXIA_HOST}

    # Ingress for the UI
    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "50m"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      hosts:
        - host: ${ONYXIA_HOST}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: wildcard-lab-tls
          hosts:
            - ${ONYXIA_HOST}

    # Environment fed to the UI container to point at your catalog
    # and your custom content (theme, pages).
    extraEnv:
      - name: CATALOG_URL
        value: ${CATALOG_URL}
      - name: CUSTOM_RESOURCES_URL
        value: ${CUSTOM_RESOURCES_URL}

    # Optional UI tweaks shown as example labels/headings
    ui:
      # These keys are merged into the UI config (kept generic on purpose).
      extraConfig:
        catalogLabels:
          productionServices: "Standardtjänster för produktion"
          dataAndMetadata: "Data- och metadatahantering"
        homepage:
          title: "SCB BoA-plattform"
          gettingStartedSlug: "getting-started-scb-boa"  # markdown filename (without .md) in your onyxia-ui-content repo

  api:
    # Ingress for the API (served under the same host on /api)
    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$1
      hosts:
        - host: ${ONYXIA_HOST}
          paths:
            - path: /api(/|$)(.*)
              pathType: Prefix
      tls:
        - secretName: wildcard-lab-tls
          hosts:
            - ${ONYXIA_HOST}

    # If the chart exposes env for API, you can add overrides here
    # extraEnv: []
